; PlatformIO Project Configuration File
; Projet : Serre Industrielle V2 - ESP32 + FreeRTOS + MQTT/TLS
; Auteur : HoraEmbedded
; Date : 2026

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -Isrc/core
    -Isrc/tasks
    -Isrc/platform
    -Iinclude

lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0

test_ignore = test/host

lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0
    beegee-tokyo/DHTesp@^1.1

