; =====================================================================
; Simulation Wokwi — publisher série, aucune dépendance réseau
; =====================================================================
[env:esp32dev_wokwi]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DPUBLISHER_SERIAL
    -Isrc/core
    -Isrc/tasks
    -Isrc/platform
    -Isrc/network
    -Iinclude
lib_deps =
    bblanchon/ArduinoJson@^7.0
build_src_filter =
    +<*>
    -<network/publisher_mqtt.cpp>
test_ignore = test/host

; =====================================================================
; Carte réelle — publisher MQTT/TLS vers HiveMQ Cloud
; =====================================================================
[env:esp32dev_hw]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DPUBLISHER_MQTT
    -Isrc/core
    -Isrc/tasks
    -Isrc/platform
    -Isrc/network
    -Iinclude
lib_deps =
    bblanchon/ArduinoJson@^7.0
    knolleary/PubSubClient@^2.8
build_src_filter =
    +<*>
    -<network/publisher_serial.cpp>
test_ignore = test/host